name: Compiler

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
    branches-ignore:
      - 'wip/**'
  workflow_dispatch:

jobs:
  notifyTelegram:
    name: Notify Telegram
    runs-on: ${{ vars.IS_USING_HOSTED_RUNNERS == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Send a message to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: |
          python ./.github/workflows/notify_telegram.py
        continue-on-error: true

  build:
    name: Build APKs
    runs-on: ${{ vars.IS_USING_HOSTED_RUNNERS == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    outputs:
      short_sha: ${{ steps.set_sha.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Create google-services.json from secret
        run: |
          mkdir -p app/src/release
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/src/release/google-services.json
          # Verify the file was created properly
          ls -la app/src/release/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Build Release APK
        env:
          SKETCHUB_API_KEY: ${{ secrets.SKETCHUB_API_KEY }}
        run: gradle assembleRelease

      - name: Set short SHA
        id: set_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Rename APK with commit hash
        run: |
          mv app/build/outputs/apk/release/app-release.apk \
             app/build/outputs/apk/release/app-release-${{ steps.set_sha.outputs.short_sha }}.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release-${{ steps.set_sha.outputs.short_sha }}
          path: app/build/outputs/apk/release/app-release-${{ steps.set_sha.outputs.short_sha }}.apk

  aggregateAndSend:
    name: Send APKs to Telegram
    runs-on: ${{ vars.IS_USING_HOSTED_RUNNERS == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: apk-release-${{ needs.build.outputs.short_sha }}
          path: ./downloaded-artifact

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install telethon

      - name: Get Git Commit Info
        run: |
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Restore Telegram session cache
        uses: actions/cache@v4
        id: telegram_session_cache
        with:
          path: bot_session.session
          key: telegram-session-${{ runner.os }}-bot_session

      - name: Send APKs to Telegram
        env:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          APK_PATH: ./downloaded-artifact/app-release-${{ needs.build.outputs.short_sha }}.apk
        run: |
          python ./.github/workflows/deploy_artifacts.py
        continue-on-error: true