name: Gemini Auto Review

on:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Run Gemini via official GitHub Action (no manual install)
      - name: Run Gemini Review
        id: gemini
        uses: google-github-actions/run-gemini-cli@v1
        with:
          args: review . --format markdown
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 3. Save Gemini output
      - name: Save Gemini output
        run: echo "${{ steps.gemini.outputs.stdout }}" > review.md

      # 4. Post review as your account
      - name: Post review comment as me
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: review.md